# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"<\n\tUserReply\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x0e\n\x06manner\x18\x03 \x01(\x02\">\n\rMannerRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x11\n\tdirection\x18\x03 \x01(\t\"\x1e\n\x0bMannerReply\x12\x0f\n\x07message\x18\x01 \x01(\t2z\n\tFunctions\x12\x31\n\x07GetInfo\x12\x12.users.UserRequest\x1a\x10.users.UserReply\"\x00\x12:\n\x0c\x43hangeManner\x12\x14.users.MannerRequest\x1a\x12.users.MannerReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERREQUEST._serialized_start=22
  _USERREQUEST._serialized_end=47
  _USERREPLY._serialized_start=49
  _USERREPLY._serialized_end=109
  _MANNERREQUEST._serialized_start=111
  _MANNERREQUEST._serialized_end=173
  _MANNERREPLY._serialized_start=175
  _MANNERREPLY._serialized_end=205
  _FUNCTIONS._serialized_start=207
  _FUNCTIONS._serialized_end=329
# @@protoc_insertion_point(module_scope)
