# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("users.proto", :syntax => :proto3) do
    add_message "users.UserRequest" do
      optional :id, :int32, 1
    end
    add_message "users.UserReply" do
      optional :nickname, :string, 1
      optional :phone, :string, 2
      optional :manner, :float, 3
    end
    add_message "users.MannerRequest" do
      optional :id, :int32, 1
      optional :amount, :float, 2
      optional :direction, :string, 3
    end
    add_message "users.MannerReply" do
      optional :message, :string, 1
    end
  end
end

module Users
  UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("users.UserRequest").msgclass
  UserReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("users.UserReply").msgclass
  MannerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("users.MannerRequest").msgclass
  MannerReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("users.MannerReply").msgclass
end
